---
- name: Download and install collections
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Ensure directory exists
      ansible.builtin.file:
        path: /opt/deeep-network/ansible-collections
        state: directory
        mode: '0755'
        recurse: true

    - name: Download zip file
      ansible.builtin.unarchive:
        src: https://github.com/deeep-network/ansible_collections/releases/download/v1.0.0/ansible-collections.zip
        dest: /opt/deeep-network/ansible-collections
        remote_src: true

    - name: Install collections
      ansible.builtin.command:
        chdir: /opt/deeep-network/ansible-collections
        cmd: ansible-galaxy install -r requirements.yml
      register: ansible_galaxy_install
      changed_when: "'Nothing to do' not in ansible_galaxy_install.stdout"
