---
driver:
  name: default
dependency:
  name: galaxy
platforms:
  - name: instance
    image: ubuntu:noble
provisioner:
  name: ansible
  playbooks:
    create: ../substrate/orbstack/create.yml
    destroy: ../substrate/orbstack/destroy.yml
    prepare: ../substrate/orbstack/prepare.yml
  inventory:
    links:
      hosts: ../inventory/
